import { erc20Abi, erc721Abi, erc1155Abi } from "./abis";
import type { Abi, Address, Hex } from "viem";
import { encodeFunctionData, isAddress, parseAbiItem } from "viem";
import deployedContracts from "~~/contracts/deployedContracts";
import externalContracts from "~~/contracts/externalContracts";

export type RecoveryAsset = {
  chainId: number;
  standard: "native" | "erc20" | "erc721" | "erc1155" | "customcall";
  contract: Address;
  tokenId?: string;
  amount?: string;
  /**
   * For `standard: "customcall"`:
   * - `functionSignature` should look like "transfer(address,uint256)" (no "function" prefix).
   * - `args` are raw user inputs; special sentinels are supported:
   *   - "$SAFE" -> substitutes the recovery/safe address
   *   - "$COMPROMISED" -> substitutes the compromised EOA address
   */
  functionSignature?: string;
  args?: string[];
  /**
   * Alternative to signature+args: raw calldata hex for the call.
   * If provided, it will be used directly as `data`.
   */
  dataHex?: Hex;
  /**
   * Value to send with the call (wei, base-10).
   * If omitted, defaults to 0.
   */
  valueWei?: string;
};

export type DelegateCall = { to: Address; value: bigint; data: Hex };

export function getDelegateForChain(chainId: number) {
  const entry =
    // Prefer explicit overrides (useful for local dev / hotfixes),
    // then fall back to autogenerated local deployments.
    (externalContracts as any)?.[chainId]?.UniversalRecoveryDelegate ??
    (deployedContracts as any)?.[chainId]?.UniversalRecoveryDelegate;
  if (!entry?.address || !entry?.abi) throw new Error(`UniversalRecoveryDelegate not deployed for chainId=${chainId}`);
  return { address: entry.address as Address, abi: entry.abi as Abi };
}

/**
 * Non-throwing variant for UI flows that want to display partial state (e.g. missing config).
 * Server-side code should generally use `getDelegateForChain` to fail fast.
 */
export function tryGetDelegateForChain(chainId: number): { address: Address; abi: Abi } | null {
  try {
    return getDelegateForChain(chainId);
  } catch {
    return null;
  }
}

export function buildAssetCalls(params: {
  compromisedAddress: Address;
  safeAddress: Address;
  assets: RecoveryAsset[];
}): DelegateCall[] {
  const calls: DelegateCall[] = [];

  const coerceArg = (input: {
    type: string;
    value: unknown;
    safeAddress: Address;
    compromisedAddress: Address;
  }): any => {
    const t = input.type.trim();
    const v = input.value;

    // Sentinel substitutions for address parameters.
    if (typeof v === "string" && t === "address") {
      const s = v.trim();
      if (s === "$SAFE") return input.safeAddress;
      if (s === "$COMPROMISED") return input.compromisedAddress;
    }

    // Arrays: accept JSON arrays.
    if (t.endsWith("[]")) {
      const inner = t.slice(0, -2);
      const raw = typeof v === "string" ? v.trim() : v;
      const arr = typeof raw === "string" ? JSON.parse(raw) : raw;
      if (!Array.isArray(arr)) throw new Error(`Expected JSON array for type ${t}`);
      return arr.map(x =>
        coerceArg({
          type: inner,
          value: x,
          safeAddress: input.safeAddress,
          compromisedAddress: input.compromisedAddress,
        }),
      );
    }

    if (t === "address") {
      const s = String(v ?? "").trim();
      if (!isAddress(s)) throw new Error(`Invalid address: ${s || "(empty)"}`);
      return s as Address;
    }
    if (t === "bool") {
      if (typeof v === "boolean") return v;
      const s = String(v ?? "")
        .trim()
        .toLowerCase();
      if (s === "true" || s === "1") return true;
      if (s === "false" || s === "0") return false;
      throw new Error(`Invalid bool: ${String(v)}`);
    }
    if (t === "string") return String(v ?? "");

    // bytes, bytes32, etc: require hex.
    if (t === "bytes" || t.startsWith("bytes")) {
      const s = String(v ?? "").trim();
      if (!s.startsWith("0x")) throw new Error(`Expected hex for ${t}`);
      return s as Hex;
    }

    // ints/uints
    if (/^u?int(\d+)?$/.test(t)) {
      const s = String(v ?? "").trim();
      if (!s) throw new Error(`Missing value for ${t}`);
      // BigInt supports 0x-prefixed hex or base-10.
      return BigInt(s);
    }

    // Fallback: try JSON for tuples/struct-like shapes (best-effort).
    if (t === "tuple") {
      const s = typeof v === "string" ? v.trim() : v;
      return typeof s === "string" ? JSON.parse(s) : s;
    }

    // Unknown type; pass through.
    return v;
  };

  for (const asset of params.assets) {
    if (asset.standard === "native") {
      // Native asset (ETH/MATIC/etc) is recovered by `executeBatchRecovery` sweeping the compromised EOA balance
      // to the recovery address at the end. No explicit call needed.
      continue;
    }

    if (asset.standard === "customcall") {
      const dataHexRaw = (asset.dataHex ?? null) as Hex | null;
      if (dataHexRaw && typeof dataHexRaw === "string" && dataHexRaw.trim()) {
        const dataHex = dataHexRaw.trim() as Hex;
        if (!dataHex.startsWith("0x")) throw new Error("customcall.dataHex must be 0x-prefixed hex");
        const valueWei = asset.valueWei ? BigInt(String(asset.valueWei).trim()) : 0n;
        calls.push({ to: asset.contract, value: valueWei, data: dataHex });
        continue;
      }

      const sigRaw = String(asset.functionSignature ?? "").trim();
      if (!sigRaw) throw new Error("Missing functionSignature for customcall");
      const sig = sigRaw.startsWith("function ") ? sigRaw.slice("function ".length).trim() : sigRaw;
      const abiItem = parseAbiItem(`function ${sig}`);
      if (abiItem.type !== "function") throw new Error("customcall.functionSignature must be a function signature");
      const fnName = abiItem.name;
      const inputs = Array.isArray(abiItem.inputs) ? (abiItem.inputs as any[]) : [];
      const rawArgs = Array.isArray(asset.args) ? asset.args : [];
      if (rawArgs.length !== inputs.length) {
        throw new Error(`Arg count mismatch for ${sig}: expected ${inputs.length} got ${rawArgs.length}`);
      }
      const coercedArgs = inputs.map((inp, i) =>
        coerceArg({
          type: String((inp as any)?.type ?? ""),
          value: rawArgs[i],
          safeAddress: params.safeAddress,
          compromisedAddress: params.compromisedAddress,
        }),
      );
      const valueWei = asset.valueWei ? BigInt(String(asset.valueWei).trim()) : 0n;
      calls.push({
        to: asset.contract,
        value: valueWei,
        data: encodeFunctionData({
          abi: [abiItem] as unknown as Abi,
          functionName: fnName as any,
          args: coercedArgs as any,
        }) as Hex,
      });
      continue;
    }

    if (asset.standard === "erc20") {
      const amount = BigInt(asset.amount ?? "0");
      calls.push({
        to: asset.contract,
        value: 0n,
        data: encodeFunctionData({
          abi: erc20Abi,
          functionName: "transfer",
          args: [params.safeAddress, amount],
        }),
      });
      continue;
    }

    if (asset.standard === "erc721") {
      if (typeof asset.tokenId === "undefined") throw new Error("Missing tokenId for ERC-721 asset");
      const tokenId = BigInt(asset.tokenId);
      calls.push({
        to: asset.contract,
        value: 0n,
        data: encodeFunctionData({
          abi: erc721Abi,
          // `safeTransferFrom` will revert when the destination is a contract that does not implement IERC721Receiver
          // (e.g. some Safe/fallback-handler setups). `transferFrom` is broadly supported and avoids that check.
          functionName: "transferFrom",
          args: [params.compromisedAddress, params.safeAddress, tokenId],
        }),
      });
      continue;
    }

    if (asset.standard === "erc1155") {
      if (typeof asset.tokenId === "undefined") throw new Error("Missing tokenId for ERC-1155 asset");
      const tokenId = BigInt(asset.tokenId);
      const amount = BigInt(asset.amount ?? "0");
      calls.push({
        to: asset.contract,
        value: 0n,
        data: encodeFunctionData({
          abi: erc1155Abi,
          functionName: "safeTransferFrom",
          args: [params.compromisedAddress, params.safeAddress, tokenId, amount, "0x"],
        }),
      });
      continue;
    }
  }

  return calls;
}

export function encodeExecuteBatch(params: {
  chainId: number;
  recoveryAddress: Address;
  calls: DelegateCall[];
  authorizer: Address;
  nonce: bigint;
  deadline: bigint;
  signature: Hex;
}): Hex {
  const { abi } = getDelegateForChain(params.chainId);
  return encodeFunctionData({
    abi,
    functionName: "executeBatchRecovery",
    args: [
      params.recoveryAddress,
      params.calls.map(c => ({ to: c.to, value: c.value, data: c.data })),
      params.authorizer,
      params.nonce,
      params.deadline,
      params.signature,
    ],
  }) as Hex;
}
