name: CI

on:
  push:
    branches:
      - main
      - fix/*
      - ci/*
  pull_request:
    branches:
      - main

jobs:
  lint-and-build-frontend:
    name: Lint & Build Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Next.js Lint
        run: yarn next:lint --max-warnings=0

      - name: Next.js Type Check
        run: yarn next:check-types

      - name: Next.js Build
        run: yarn next:build
        env:
          NEXT_PUBLIC_ALCHEMY_API_KEY: ${{ secrets.NEXT_PUBLIC_ALCHEMY_API_KEY }}
          NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID }}

  test-contracts:
    name: Test & Build Smart Contracts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run Foundry tests
        run: |
          cd packages/foundry
          forge test -vvv
